// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance-display': string;
  'balance-display__balance': string;
}
export const cssExports: CssExports;
export default cssExports;
